[package]
name = "anemoi"
version = "0.1.0"
authors = ["Robin Salen <salenrobin@gmail.com>"]
edition = "2021"
description = "New Design Techniques for Efficient Arithmetization-Oriented Hash Functions:Anemoi Permutations and Jive Compression Mode"
readme = "README.md"
license = "MIT"
repository = "https://github.com/anemoi-hash/anemoi-rust"
homepage = "https://github.com/anemoi-hash/anemoi-rust"
keywords = ["cryptography", "hash", "hash-function", "anemoi", "sponge", "compression", "zero-knowledge"]
categories = ["cryptography"]



[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/utils" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/algebra" }
ark-curve25519 = { git = "https://github.com/arkworks-rs/algebra" }
ark-pallas = { git = "https://github.com/arkworks-rs/algebra" }
ark-vesta = { git = "https://github.com/arkworks-rs/algebra" }

[dependencies]
ark-ff = { version="^0.4.0", default-features = false }
ark-bls12-377 = { version="^0.4.0", default-features = false, optional = true }
ark-bls12-381 = { version="^0.4.0", default-features = false, optional = true }
ark-bn254 = { version="^0.4.0", default-features = false, optional = true }
ark-ec = { version="^0.4.0", default-features = false }
ark-pallas = { version="^0.4.0", default-features = false, optional = true }
ark-serialize = { version="^0.4.0", default-features = false }
ark-std = { version="^0.4.0", default-features = false }
getrandom = { version = "0.2", default-features = false, features = ["js"] }
rand_core = { version = "0.6.2", default-features = false, features = ["getrandom"] }
unroll = { version = "0.1.5" }

[dev-dependencies]
ark-algebra-test-templates = { version="^0.4.0" }
criterion = "0.3"

[features]
default = [
    "std",
    # "bls12_377",
    "bls12_381",
    # "bn_254",
    "ed_on_bls12_377",
    "jubjub",
    "pallas",
    "vesta",
]

std = [
    "ark-std/std",
    "ark-ff/std",
    "ark-ec/std",
    "rand_core/std"
]

bls12_377 = ["ark-bls12-377/curve"]
bls12_381 = ["ark-bls12-381/curve"]
bn_254 = ["ark-bn254/curve"]
ed_on_bls12_377 = ["ark-bls12-377/scalar_field"]
jubjub = ["ark-bls12-381/scalar_field"]
pallas = ["ark-pallas/curve"]
vesta = ["ark-pallas/scalar_field"]

asm = ["ark-ff/asm"]

[[bench]]
name = "bls12_377"
harness = false
required-features = ["bls12_377"]

[[bench]]
name = "bls12_381"
harness = false
required-features = ["bls12_381"]

[[bench]]
name = "bn_254"
harness = false
required-features = ["bn_254"]

[[bench]]
name = "ed_on_bls12_377"
harness = false
required-features = ["ed_on_bls12_377"]

[[bench]]
name = "jubjub"
harness = false
required-features = ["jubjub"]

[[bench]]
name = "pallas"
harness = false
required-features = ["pallas"]

[[bench]]
name = "vesta"
harness = false
required-features = ["vesta"]
